### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by allankiezel** [MorningCoffeeDev/ACR-NFC-Reader-PhoneGap-Plugin#10]
Hey there,

I'm trying to install this into an ionic project with no luck. I get the plugin installed, but it says Cannot find name 'ACR' when building. 

Thanks!

**Comment by online123be** [comment]
Were you able to fix it?

**Comment by HashNotAdam** [comment]
Sorry, we were using the ACR readers for a closed-loop payments platform but transitioned to a solution based upon the traditional payments networks many years ago. As such, we have not kept this plugin up-to-date and I'm not sure I even know where we put our test NFC units.

Given how much Cordova has changed over the years, I would be surprised if this plugin still works and I think it would be best if we mark this repo as deprecated
